version: "3.3"

services:

  nginx:
    image: nginx:latest
    ports:
      - "5000:80"
    volumes:
      # - ./static:/srv/www/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  nodejs_a:
    image: node:latest
    ports:
      - '5001:5000'
    environment: 
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    volumes:
      - ./nodejs:/home/app
    command: "node index.js"

  nodejs_b:
    image: node:latest
    ports:
      - '5002:5000'
    environment: 
      NODE_ENV: production
      name: yusuf
    working_dir: /home/app
    restart: always
    volumes:
      - ./nodejs:/home/app
    command: "node index.js"